export const keyMap = {
	' ': 'Spacebar',
	'?': '/',
	'>': '.',
	'<': ',',
	':': ';',
	'"': "'",
	'{': '[',
	'}': ']',
	_: '-',
	'+': '=',
	'|': '\\',
	'~': '`',
	'!': '1',
	'@': '2',
	'#': '3',
	$: '4',
	'%': '5',
	'^': '6',
	'&': '7',
	'*': '8',
	'(': '9',
	')': '0'
};

export const expectedKeys = {
	Q: 'LEFT_PINKY',
	A: 'LEFT_PINKY',
	Z: 'LEFT_PINKY',
	W: 'LEFT_RING',
	S: 'LEFT_RING',
	X: 'LEFT_RING',
	E: 'LEFT_MIDDLE',
	D: 'LEFT_MIDDLE',
	C: 'LEFT_MIDDLE',
	R: 'LEFT_INDEX',
	F: 'LEFT_INDEX',
	V: 'LEFT_INDEX',
	T: 'LEFT_INDEX',
	G: 'LEFT_INDEX',
	B: 'LEFT_INDEX',
	Y: 'RIGHT_INDEX',
	H: 'RIGHT_INDEX',
	N: 'RIGHT_INDEX',
	U: 'RIGHT_INDEX',
	J: 'RIGHT_INDEX',
	M: 'RIGHT_INDEX',
	I: 'RIGHT_MIDDLE',
	K: 'RIGHT_MIDDLE',
	',': 'RIGHT_MIDDLE',
	O: 'RIGHT_RING',
	L: 'RIGHT_RING',
	'.': 'RIGHT_RING',
	P: 'RIGHT_PINKY',
	';': 'RIGHT_PINKY',
	'/': 'RIGHT_PINKY',
	"'": 'RIGHT_PINKY',
	'[': 'RIGHT_PINKY',
	']': 'RIGHT_PINKY'
};
